### ISSUE TITLE
Investigate updating BDS C libraries and L2 linker.

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/pmince#15]
As noted on AMETHYST-USERS by Brian Hess on 6-Jun-1984:
```text
6-Jun-84 21:05:46-MDT,1059;000000000000
Return-Path: <Hess.Unicorn@MIT-MULTICS.ARPA>
Received: from MIT-MULTICS.ARPA by SIMTEL20.ARPA with TCP; Wed 6 Jun 84 21:05:34-MDT
Date:  Wed, 6 Jun 84 22:55 EDT
From:  Hess@MIT-MULTICS.ARPA
Subject:  Mince under CP/M 3.0
To:  amethyst-users@SIMTEL20.ARPA
Message-ID:  <840607025556.446512@MIT-MULTICS.ARPA>

We use BDS C 1.5 and L2 1.3 internally; I'll check with L2's author to
see if 1.3 is distributed, and if so or not, why so or not...  You can
use 1.45 or 1.45a to compile your old source code, andif you want to use
1.5, you can get an update from Mark of the Unicorn for your old disk
and $25.

Mince's author says that the distributed Mince works properly under CP/M
3.0, and can't think of any good things that might be wrong to cause
intermittent deviation in some COMMn.C routines.

He also said that on CP/M, the printf does indeed send stuff out right
away, and that TERM.C doesn't use printf (at least not the standard
large version) anyway; therefore, that can't be the problem with some
messages not appearing.

Brian
```

**Comment by johnsonjh** [comment]
```text
1-Dec-83 18:09:29-MST,888;000000000000
Return-Path: <bridger@rand-unix>
Received: from rand-unix by SIMTEL20.ARPA with TCP; Thu 1 Dec 83 18:08:59-MST
Date: Thursday,  1 Dec 1983 16:52-PST
To: kevinw@SU-DSN, amethyst-users @SIMTEL20
CC: bridger@rand-unix
Subject: MINCE with user numbers
In-reply-to: Your message of Monday, 28 Nov 1983 13:37-PST.
From: bridger@rand-unix

	Kevin @SU-DSN recently noted the limitation of using the
Mince editor in different user areas.  I think Leor's new compiler
could do the trick:
	Mince would be helped a lot if it were re-compiled in bds c 1.5,
which supports user-number file references.  By putting the swap file
in user 0 and using ZCPR or a similar command processor that uses
a search path to user 0, you could invoke mince from any user/drive
and also read/write files from any user/drive.
	Perhaps MOTU would consider issuing this much of an update?
--bridger.
```

**Comment by johnsonjh** [comment]
```text
 2-Dec-83 16:37:13-MST,954;000000000000
Mail-From: WANCHO created at  2-Dec-83 16:32:31
Date: 2 Dec 1983  16:32 MST (Fri)
Message-ID: <WANCHO.11972373613.BABYL@SIMTEL20>
From: "Frank J. Wancho" <WANCHO@SIMTEL20>
To:   AMETHYST-USERS@SIMTEL20
Subject: Mince/BDSC-1.50a/User areas

Apparently the new copies of Mince are compiled with BDSC 1.50a.  But,
they have no plans to update existing users with the newly compiled
version, because of the paucity of users of CP/M Mince today, even
fewer who have user number areas, and the fact that nobody at MotU is
willing to pick a price for the update that is so minor.  Word is that
they don't object to people trading disks with each other to get the
latest stuff, but they don't think distributors and dealers should be
obligated to provide such a service without a profit.  So MotU quietly
released it internally and is not offering its usual free updates, nor
any at all for that matter, this time around... (sigh...)

--Frank
```

**Comment by johnsonjh** [comment]
```text
4-Nov-83 17:55:13-MST,770;000000000000
Return-Path: <LMTRA@SRI-KL.ARPA>
Received: from SRI-KL.ARPA by SIMTEL20.ARPA with TCP; Fri 4 Nov 83 17:54:49-MST
Date:  4 Nov 1983 1127-PST
From: Lmtra at SRI-KL
Subject: Linking Mince 2.6
To:   BNH at MIT-ML
cc:   ROODE at SRI-AI, AMETHYST-USERS at SIMTEL20


Brian,
I caught a message of yours about Mince and since I've had nothing but
exasperation getting anything technical out of M of the U, I thought I'd
give you (and the rest of the group) a try.

I've tried to link Mince 2.6 (using the L2 submit supplied that includes
the new VBUFF3) and the resulting module just hangs.  I've made no source
changes as yet, so I'm a bit discouraged.  Any advice?

I'm running under CP/M-80 on a Heath 89.

Thanks,
Leon Traister (LMTRA@SRI-KL)
```

**Comment by johnsonjh** [comment]
```text
15-Nov-83 18:20:09-MST,1018;000000000000
Return-Path: <Hess.Unicorn@MIT-MULTICS.ARPA>
Received: from MIT-MULTICS.ARPA by SIMTEL20.ARPA with TCP; Tue 15 Nov 83 18:19:30-MST
Date:  15 November 1983 20:15 est
From:  Hess.Unicorn at MIT-MULTICS
Subject:  Linking Mince 2.6
To:  amethyst-users at SIMTEL20
cc:  Lmtra at SRI-KL

The usual flake is:  Is L2 going into 2-pass mode?  If so, you have two
choices: (1) Run your CP/M with a bigger TPA so it only takes one pass,
or (2) Change your L2 line so that it reads:

l2 mince bndings comm1 comm2 comm3 vbuff1 vbuff3 vbuff2 -l support aterm
term util

i.e., move the "aterm" to the right-hand side of the "-l".

what used to be happening is that L2 found duplicate symbols in term and
aterm on its first pass, choose one of the files to use them from
(aterm, since it passed across it first), but then the second pass never
knew where the routine really came from, so it just took whatever it
could get, sometimes from the second one, and if they were different
sizes, it got all messed up.
```

**Comment by johnsonjh** [comment]
Work has begun to automate cross-build using BDS C 1.6
